"""extend audit events for security audit trail

Revision ID: 34c12cca2961
Revises: da5ca92a63cb
Create Date: 2026-10-08 12:00:16.652963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c12cca2961'
down_revision: Union[str, Sequence[str], None] = 'da5ca92a63cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_audit_events', sa.Column('role', sa.String(length=32), nullable=True))
    op.add_column('auth_audit_events', sa.Column('result', sa.String(length=16), nullable=True))
    op.add_column('auth_audit_events', sa.Column('resource_type', sa.String(length=32), nullable=True))
    op.add_column('auth_audit_events', sa.Column('resource_id', sa.String(length=64), nullable=True))
    op.add_column('auth_audit_events', sa.Column('detail', sa.JSON(), nullable=True))
    op.add_column('auth_audit_events', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('auth_audit_events', sa.Column('user_agent', sa.String(length=256), nullable=True))
    op.add_column('auth_audit_events', sa.Column('request_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_auth_audit_events_resource_id'), 'auth_audit_events', ['resource_id'], unique=False)
    # ### end Alembic commands ###
    # Existing auth events get a result derived from their success flag.
    op.execute("UPDATE auth_audit_events SET result = CASE WHEN success THEN 'SUCCESS' ELSE 'FAILURE' END WHERE result IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_audit_events_resource_id'), table_name='auth_audit_events')
    op.drop_column('auth_audit_events', 'request_id')
    op.drop_column('auth_audit_events', 'user_agent')
    op.drop_column('auth_audit_events', 'ip_address')
    op.drop_column('auth_audit_events', 'detail')
    op.drop_column('auth_audit_events', 'resource_id')
    op.drop_column('auth_audit_events', 'resource_type')
    op.drop_column('auth_audit_events', 'result')
    op.drop_column('auth_audit_events', 'role')
    # ### end Alembic commands ###
