"""add document indexing columns (Sprint 5 RAG)

Revision ID: da5ca92a63cb
Revises: b7fdd7d920be
Create Date: 2026-10-07 15:40:21.736413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5ca92a63cb'
down_revision: Union[str, Sequence[str], None] = 'b7fdd7d920be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'indexed_at')
    op.drop_column('documents', 'chunk_count')
    # ### end Alembic commands ###
